### ISSUE TITLE
Existing VCN - How to spin the Master/Standby instance in OCI

### ISSUE THREAD

**Issue by helpenterprise** [oracle-devrel/terraform-oci-arch-postgresql#12]
(1) How to spin the Master/Standby instance into existing VCN. It's not giving option during deployment under resource manager to choose the existing VCN. If give manual cidr raning inside the console then it's give error
(2) If need to spin 2 Postgres environment using this, then how to ensure it will not conflict with the existing 1st instances resources name  inside the same vcn.

**Comment by helpenterprise** [comment]
Need to deploy multiple High availability environments into an existing VCN, if this can be supported using this code. Deployed one Successfully but there is no option for existing VCN.

**Comment by lfeldman** [comment]
@helpenterprise this code is treated as a starting point to build customized deployments. You can check [the examples](https://github.com/oracle-devrel/terraform-oci-arch-postgresql/tree/main/examples) and use those snippets as a starting point in your Terraform journey.
