### ISSUE TITLE
Connection on remote.tf getting time out error

### ISSUE THREAD

**Issue by pranavp12** [oracle-devrel/terraform-oci-arch-postgresql#14]
Hi Team,

When we try to use this code to spin up postgresql instances, it works fine until remote-exec and times out before running "postgresql_master_initdb"

It completes successfully on multiple retries (3 times) without making any changes. We tried increasing session timeout but even that did not help. Any help in troubleshooting what could be the probable cause? Anyone else facing similar issue?

module.oci-postgresql.null_resource.postgresql_master_initdb (remote-exec):   User: ####
module.oci-postgresql.null_resource.postgresql_master_initdb (remote-exec):   Password: false
module.oci-postgresql.null_resource.postgresql_master_initdb (remote-exec):   Private key: true
module.oci-postgresql.null_resource.postgresql_master_initdb (remote-exec):   Certificate: false
module.oci-postgresql.null_resource.postgresql_master_initdb (remote-exec):   SSH Agent: false
module.oci-postgresql.null_resource.postgresql_master_initdb (remote-exec):   Checking Host Key: false
module.oci-postgresql.null_resource.postgresql_master_initdb (remote-exec):   Target Platform: unix
module.oci-postgresql.null_resource.postgresql_master_initdb (remote-exec): Using configured bastion host...
module.oci-postgresql.null_resource.postgresql_master_initdb (remote-exec):   Host: host.bastion.me-jeddah-1.oci.oraclecloud.com
module.oci-postgresql.null_resource.postgresql_master_initdb (remote-exec):   User: #####
module.oci-postgresql.null_resource.postgresql_master_initdb (remote-exec):   Password: false
module.oci-postgresql.null_resource.postgresql_master_initdb (remote-exec):   Private key: true
module.oci-postgresql.null_resource.postgresql_master_initdb (remote-exec):   Certificate: false
module.oci-postgresql.null_resource.postgresql_master_initdb (remote-exec):   SSH Agent: false
module.oci-postgresql.null_resource.postgresql_master_initdb (remote-exec):   Checking Host Key: false
module.oci-postgresql.null_resource.postgresql_master_initdb: Still creating... [10m0s elapsed]
╷
│ Error: remote-exec provisioner error
│ 
│   with module.oci-postgresql.null_resource.postgresql_master_initdb,
│   on .terraform/modules/oci-postgresql/remote.tf line 251, in resource "null_resource" "postgresql_master_initdb":
│  251:   provisioner "remote-exec" {
│ 
│ timeout - last error: Error connecting to bastion: ssh: handshake failed:
│ ssh: unable to authenticate, attempted methods [none publickey], no
│ supported methods remain
╵

**Comment by rhegde2** [comment]
hi @lfeldman Did you get a chance to look into this issue? 
Thanks.

**Comment by lfeldman** [comment]
Hi @rhegde2, we will add this to our queue.

**Comment by lfeldman** [comment]
I am not able to reproduce your error: 
<img width="1353" alt="image" src="https://user-images.githubusercontent.com/19390609/186397794-140e96f8-abd3-4684-ae7d-355b51caf097.png">

**Comment by lfeldman** [comment]
No response from the customer. Closing the issue.
