### ISSUE TITLE
Can not execute successfully in private subnet but worked in Public subnet

### ISSUE THREAD

**Issue by SimonChou168** [oracle-devrel/terraform-oci-arch-postgresql#17]
Hi Expert,
I found it can not execute successfully in private subnet. But when I change the stack config to unselect “Create in Private Subnet” and it execute successfully. It's so strange.

Regards,
Simon

**Comment by nugoncal** [comment]
Hi, can you share the logs? 
I tested this repo last week, both from ORM and Terraform CLI, and I had no issues. With private subnet.

**Comment by SimonChou168** [comment]
[Private subnet.log](https://github.com/oracle-devrel/terraform-oci-arch-postgresql/files/9663822/Private.subnet.log)
[Public subnet.log](https://github.com/oracle-devrel/terraform-oci-arch-postgresql/files/9663827/Public.subnet.log)
Hi,

          Thanks so much!
          Attached is the two log for your reference.
          The “Private subnet.log” is the failed log.
          The “Public subnet.log” is the successful log.

Best regards
Simon Chou

**Comment by nugoncal** [comment]
We have confirmed with Simon that the deployment is working on ORM on reapply (Apply a second time, without destroying). This is a necessary workaround at the moment for the private subnet scenario, due to OCI Bastion service issues.

**Comment by SimonChou168** [comment]
Yes, Thanks for your help.
