### ISSUE TITLE
VM.Standard3.Flex shapes Customization

### ISSUE THREAD

**Issue by Mosad** [oracle-devrel/terraform-oci-arch-postgresql#18]
When I try to create the postgreSQL cluster with VM.Standard3.Flex shapes, the stack doesn't show me number of cores or memory to assign to the compute instances. Is there a way fix it?

![image](https://user-images.githubusercontent.com/515122/192773642-203c30a8-c7d0-45e7-a821-a225b52ba912.png)

![image](https://user-images.githubusercontent.com/515122/192773720-e7f55072-5048-440a-baf5-819af188c90d.png)

**Comment by lfeldman** [comment]
@Mosad we have added support for VM.Standard3.Flex into the code. Thanks for highlighting the issue.
