### ISSUE TITLE
 Enable the Bastion plugin on the target instance before creating the session.

### ISSUE THREAD

**Issue by bhushanarora2006** [oracle-devrel/terraform-oci-arch-postgresql#8]
For 1 of the standby , it's giving following error. At instance level already bastion plugin enabled for all 3 instance:

 To create a Managed SSH session, the Bastion plugin must be in the RUNNING state on the target instance, but the plugin is not running on <<OCID of Instance>>. Enable the Bastion plugin on the target instance before creating the session.

**Comment by lfeldman** [comment]
@bhushanarora2006, Sometimes bastion plugin startup on target VM takes longer and bastion session cannot be established successfully. Re-try the deployment, please.

**Comment by lfeldman** [comment]
@bhushanarora2006 please check [our latest release](https://github.com/oracle-devrel/terraform-oci-arch-postgresql/releases/tag/v1.4.3). We have made slight adjustments to the bastion session and bastion agent by introducing checker functionality. In our tenancy, it has to lead to a more stable exec of the stack.

**Comment by bhushanarora2006** [comment]
Ok, thanks for the update. Earlier I retried and it was working for me.

**Comment by lfeldman** [comment]
Ok. Thank You :) Closing the ticket.
